language: go

go:
  - 1.13

services:
  - docker

script:
  - set -e
  - make docker-login
  - DOCKER_REPO=$TRAVIS_REPO_SLUG DOCKER_TAG=$TRAVIS_TAG make docker-build
  - DOCKER_REPO=$TRAVIS_REPO_SLUG DOCKER_TAG=$TRAVIS_TAG make docker-push
