language: go

go:
  - 1.13

services:
  - docker

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script:
        - set -e
        - make clean
        - make docker-login
        - DOCKER_REPO=$TRAVIS_REPO_SLUG DOCKER_TAG="$(echo $TRAVIS_TAG | sed -Ee 's/^v([0-9]+\.[0-9]+(\.[0-9]+)?)/\1/')" make docker-build
        - DOCKER_REPO=$TRAVIS_REPO_SLUG DOCKER_TAG="$(echo $TRAVIS_TAG | sed -Ee 's/^v([0-9]+\.[0-9]+(\.[0-9]+)?)/\1/')" make docker-push
    - stage: deploy
      if: tag IS present
      script: VERSION="$(echo $TRAVIS_TAG | sed -Ee 's/^v([0-9]+\.[0-9]+(\.[0-9]+)?)/\1/')" make dist
      deploy:
        provider: releases
        api_key:
          secure: "Nd1QIEZOgN9Rx97tkSSVvHsOTNtoMRyGg5yccoSL64iMXEyOEBN8eWUwByjtigWaRbAOTfNPYanF1v1Ds4HVJwjB5nWUh6yuuchoOZHjemR0eX9jsqFXjXLSafDNmoVrVu8X/Jb/fa58pDfEaplqgfr4N6l21bZb375SXmEa1c9t6wOSfM+goKlV4GWKTxOXLdr/FJ3OhQTr73Vc6UrwQWgAptsPIcAj/7SYXqAiU9htcBQYmCCjDJ9+pWkpQdDwvYwJBDEAx5etsft++tFPCR20h48lSAt+Qz17P85QQyqa9KPn3+lXWC+Gdq+7fN0t3fIqzU321Oicg30t4ETbADj+qyFrITKqzil6hyBqZoCC2tdpONSiFmQKCIYHG//Fet39BVMO5jtGydnapTvO2EALYNc3my4EqzFGlgGZ/NTqGod5KolfKeMMjjCmY6iW0ivxx2yuCP6gP2eHgRi3nqFfb5MM4suA3KPQHWaL2uo1IDMnBzWaAnUr1Zhg5si/5th9bQmAlSHNDorxYm4hwnYuQFzbs3eZSJW1uMX859uDIypuqhCgcA0Ij+Uy9Nf4Nhez8qChenAaoe7KSlO12xH7sDa0ZN83nUUYqj6Raa8iK9jSBl4DfsfCSGdOzKwzacFMGiovMKZhpRpHNe18uuNhS9MFk/GOY1FzvQcFhEQ="
        file_glob: true
        file: dist/*.tgz
        skip_cleanup: true
        on:
          tags: true
